// created
export const CREATE_PROCUREMENT_HOTEL_LOADING = 'create_PROCUREMENT_HOTEL_loading'
export const CREATE_PROCUREMENT_HOTEL_SUCCESS = 'create_PROCUREMENT_HOTEL_success'
export const CREATE_PROCUREMENT_HOTEL_ERROR = 'create_PROCUREMENT_HOTEL_error'
// updated
export const UPDATE_PROCUREMENT_HOTEL_LOADING = 'update_PROCUREMENT_HOTEL_loading'
export const UPDATE_PROCUREMENT_HOTEL_SUCCESS = 'update_PROCUREMENT_HOTEL_success'
export const UPDATE_PROCUREMENT_HOTEL_ERROR = 'update_PROCUREMENT_HOTEL_error'
// deleted
export const DELETE_PROCUREMENT_HOTEL_LOADING = 'delete_PROCUREMENT_HOTEL_loading'
export const DELETE_PROCUREMENT_HOTEL_SUCCESS = 'delete_PROCUREMENT_HOTEL_success'
export const DELETE_PROCUREMENT_HOTEL_ERROR = 'delete_PROCUREMENT_HOTEL_error'
