// created
export const CREATE_SERVICE_KENDARAAN_LOADING = 'create_SERVICE_KENDARAAN_loading'
export const CREATE_SERVICE_KENDARAAN_SUCCESS = 'create_SERVICE_KENDARAAN_success'
export const CREATE_SERVICE_KENDARAAN_ERROR = 'create_SERVICE_KENDARAAN_error'
// updated
export const UPDATE_SERVICE_KENDARAAN_LOADING = 'update_SERVICE_KENDARAAN_loading'
export const UPDATE_SERVICE_KENDARAAN_SUCCESS = 'update_SERVICE_KENDARAAN_success'
export const UPDATE_SERVICE_KENDARAAN_ERROR = 'update_SERVICE_KENDARAAN_error'
// deleted
export const DELETE_SERVICE_KENDARAAN_LOADING = 'delete_SERVICE_KENDARAAN_loading'
export const DELETE_SERVICE_KENDARAAN_SUCCESS = 'delete_SERVICE_KENDARAAN_success'
export const DELETE_SERVICE_KENDARAAN_ERROR = 'delete_SERVICE_KENDARAAN_error'
