// created
export const CREATE_AKTIVITAS_COURIER_LOADING = 'create_AKTIVITAS_COURIER_loading'
export const CREATE_AKTIVITAS_COURIER_SUCCESS = 'create_AKTIVITAS_COURIER_success'
export const CREATE_AKTIVITAS_COURIER_ERROR = 'create_AKTIVITAS_COURIER_error'
// updated
export const UPDATE_AKTIVITAS_COURIER_LOADING = 'update_AKTIVITAS_COURIER_loading'
export const UPDATE_AKTIVITAS_COURIER_SUCCESS = 'update_AKTIVITAS_COURIER_success'
export const UPDATE_AKTIVITAS_COURIER_ERROR = 'update_AKTIVITAS_COURIER_error'
// deleted
export const DELETE_AKTIVITAS_COURIER_LOADING = 'delete_AKTIVITAS_COURIER_loading'
export const DELETE_AKTIVITAS_COURIER_SUCCESS = 'delete_AKTIVITAS_COURIER_success'
export const DELETE_AKTIVITAS_COURIER_ERROR = 'delete_AKTIVITAS_COURIER_error'
