// created
export const CREATE_AKTIVITAS_SECURITY_LOADING = 'create_AKTIVITAS_SECURITY_loading'
export const CREATE_AKTIVITAS_SECURITY_SUCCESS = 'create_AKTIVITAS_SECURITY_success'
export const CREATE_AKTIVITAS_SECURITY_ERROR = 'create_AKTIVITAS_SECURITY_error'
// updated
export const UPDATE_AKTIVITAS_SECURITY_LOADING = 'update_AKTIVITAS_SECURITY_loading'
export const UPDATE_AKTIVITAS_SECURITY_SUCCESS = 'update_AKTIVITAS_SECURITY_success'
export const UPDATE_AKTIVITAS_SECURITY_ERROR = 'update_AKTIVITAS_SECURITY_error'
// deleted
export const DELETE_AKTIVITAS_SECURITY_LOADING = 'delete_AKTIVITAS_SECURITY_loading'
export const DELETE_AKTIVITAS_SECURITY_SUCCESS = 'delete_AKTIVITAS_SECURITY_success'
export const DELETE_AKTIVITAS_SECURITY_ERROR = 'delete_AKTIVITAS_SECURITY_error'
