// created
export const CREATE_EVALUASI_SUPPLIER_LOADING = 'create_EVALUASI_SUPPLIER_loading'
export const CREATE_EVALUASI_SUPPLIER_SUCCESS = 'create_EVALUASI_SUPPLIER_success'
export const CREATE_EVALUASI_SUPPLIER_ERROR = 'create_EVALUASI_SUPPLIER_error'
// updated
export const UPDATE_EVALUASI_SUPPLIER_LOADING = 'update_EVALUASI_SUPPLIER_loading'
export const UPDATE_EVALUASI_SUPPLIER_SUCCESS = 'update_EVALUASI_SUPPLIER_success'
export const UPDATE_EVALUASI_SUPPLIER_ERROR = 'update_EVALUASI_SUPPLIER_error'
// deleted
export const DELETE_EVALUASI_SUPPLIER_LOADING = 'delete_EVALUASI_SUPPLIER_loading'
export const DELETE_EVALUASI_SUPPLIER_SUCCESS = 'delete_EVALUASI_SUPPLIER_success'
export const DELETE_EVALUASI_SUPPLIER_ERROR = 'delete_EVALUASI_SUPPLIER_error'
