// upload
export const UPLOAD_ANGGARAN_INVESTASI_LOADING = 'UPLOAD_ANGGARAN_INVESTASI_loading'
export const UPLOAD_ANGGARAN_INVESTASI_SUCCESS = 'UPLOAD_ANGGARAN_INVESTASI_success'
export const UPLOAD_ANGGARAN_INVESTASI_ERROR = 'UPLOAD_ANGGARAN_INVESTASI_error'
