// created
export const CREATE_FIXED_ASSET_ANGGARAN_LOADING = 'create_FIXED_ASSET_ANGGARAN_loading'
export const CREATE_FIXED_ASSET_ANGGARAN_SUCCESS = 'create_FIXED_ASSET_ANGGARAN_success'
export const CREATE_FIXED_ASSET_ANGGARAN_ERROR = 'create_FIXED_ASSET_ANGGARAN_error'
// updated
export const UPDATE_FIXED_ASSET_ANGGARAN_LOADING = 'update_FIXED_ASSET_ANGGARAN_loading'
export const UPDATE_FIXED_ASSET_ANGGARAN_SUCCESS = 'update_FIXED_ASSET_ANGGARAN_success'
export const UPDATE_FIXED_ASSET_ANGGARAN_ERROR = 'update_FIXED_ASSET_ANGGARAN_error'
// deleted
export const DELETE_FIXED_ASSET_ANGGARAN_LOADING = 'delete_FIXED_ASSET_ANGGARAN_loading'
export const DELETE_FIXED_ASSET_ANGGARAN_SUCCESS = 'delete_FIXED_ASSET_ANGGARAN_success'
export const DELETE_FIXED_ASSET_ANGGARAN_ERROR = 'delete_FIXED_ASSET_ANGGARAN_error'
