// created
export const CREATE_PENGELOLAAN_KONSUMSI_LOADING = 'create_PENGELOLAAN_KONSUMSI_loading'
export const CREATE_PENGELOLAAN_KONSUMSI_SUCCESS = 'create_PENGELOLAAN_KONSUMSI_success'
export const CREATE_PENGELOLAAN_KONSUMSI_ERROR = 'create_PENGELOLAAN_KONSUMSI_error'
// updated
export const UPDATE_PENGELOLAAN_KONSUMSI_LOADING = 'update_PENGELOLAAN_KONSUMSI_loading'
export const UPDATE_PENGELOLAAN_KONSUMSI_SUCCESS = 'update_PENGELOLAAN_KONSUMSI_success'
export const UPDATE_PENGELOLAAN_KONSUMSI_ERROR = 'update_PENGELOLAAN_KONSUMSI_error'
// deleted
export const DELETE_PENGELOLAAN_KONSUMSI_LOADING = 'delete_PENGELOLAAN_KONSUMSI_loading'
export const DELETE_PENGELOLAAN_KONSUMSI_SUCCESS = 'delete_PENGELOLAAN_KONSUMSI_success'
export const DELETE_PENGELOLAAN_KONSUMSI_ERROR = 'delete_PENGELOLAAN_KONSUMSI_error'
