// created
export const CREATE_SELEKSI_LANGSUNG_LOADING = 'create_SELEKSI_LANGSUNG_loading'
export const CREATE_SELEKSI_LANGSUNG_SUCCESS = 'create_SELEKSI_LANGSUNG_success'
export const CREATE_SELEKSI_LANGSUNG_ERROR = 'create_SELEKSI_LANGSUNG_error'
// updated
export const UPDATE_SELEKSI_LANGSUNG_LOADING = 'update_SELEKSI_LANGSUNG_loading'
export const UPDATE_SELEKSI_LANGSUNG_SUCCESS = 'update_SELEKSI_LANGSUNG_success'
export const UPDATE_SELEKSI_LANGSUNG_ERROR = 'update_SELEKSI_LANGSUNG_error'
// deleted
export const DELETE_SELEKSI_LANGSUNG_LOADING = 'delete_SELEKSI_LANGSUNG_loading'
export const DELETE_SELEKSI_LANGSUNG_SUCCESS = 'delete_SELEKSI_LANGSUNG_success'
export const DELETE_SELEKSI_LANGSUNG_ERROR = 'delete_SELEKSI_LANGSUNG_error'
