// created
export const CREATE_PROCUREMENT_CATERING_LOADING = 'create_PROCUREMENT_CATERING_loading'
export const CREATE_PROCUREMENT_CATERING_SUCCESS = 'create_PROCUREMENT_CATERING_success'
export const CREATE_PROCUREMENT_CATERING_ERROR = 'create_PROCUREMENT_CATERING_error'
// updated
export const UPDATE_PROCUREMENT_CATERING_LOADING = 'update_PROCUREMENT_CATERING_loading'
export const UPDATE_PROCUREMENT_CATERING_SUCCESS = 'update_PROCUREMENT_CATERING_success'
export const UPDATE_PROCUREMENT_CATERING_ERROR = 'update_PROCUREMENT_CATERING_error'
// deleted
export const DELETE_PROCUREMENT_CATERING_LOADING = 'delete_PROCUREMENT_CATERING_loading'
export const DELETE_PROCUREMENT_CATERING_SUCCESS = 'delete_PROCUREMENT_CATERING_success'
export const DELETE_PROCUREMENT_CATERING_ERROR = 'delete_PROCUREMENT_CATERING_error'
