// created
export const CREATE_AKTIVITAS_DRIVER_LOADING = 'create_AKTIVITAS_DRIVER_loading'
export const CREATE_AKTIVITAS_DRIVER_SUCCESS = 'create_AKTIVITAS_DRIVER_success'
export const CREATE_AKTIVITAS_DRIVER_ERROR = 'create_AKTIVITAS_DRIVER_error'
// updated
export const UPDATE_AKTIVITAS_DRIVER_LOADING = 'update_AKTIVITAS_DRIVER_loading'
export const UPDATE_AKTIVITAS_DRIVER_SUCCESS = 'update_AKTIVITAS_DRIVER_success'
export const UPDATE_AKTIVITAS_DRIVER_ERROR = 'update_AKTIVITAS_DRIVER_error'
// deleted
export const DELETE_AKTIVITAS_DRIVER_LOADING = 'delete_AKTIVITAS_DRIVER_loading'
export const DELETE_AKTIVITAS_DRIVER_SUCCESS = 'delete_AKTIVITAS_DRIVER_success'
export const DELETE_AKTIVITAS_DRIVER_ERROR = 'delete_AKTIVITAS_DRIVER_error'
