// created
export const CREATE_PENUNJUKAN_LANGSUNG_LOADING = 'create_PENUNJUKAN_LANGSUNG_loading'
export const CREATE_PENUNJUKAN_LANGSUNG_SUCCESS = 'create_PENUNJUKAN_LANGSUNG_success'
export const CREATE_PENUNJUKAN_LANGSUNG_ERROR = 'create_PENUNJUKAN_LANGSUNG_error'
// updated
export const UPDATE_PENUNJUKAN_LANGSUNG_LOADING = 'update_PENUNJUKAN_LANGSUNG_loading'
export const UPDATE_PENUNJUKAN_LANGSUNG_SUCCESS = 'update_PENUNJUKAN_LANGSUNG_success'
export const UPDATE_PENUNJUKAN_LANGSUNG_ERROR = 'update_PENUNJUKAN_LANGSUNG_error'
// deleted
export const DELETE_PENUNJUKAN_LANGSUNG_LOADING = 'delete_PENUNJUKAN_LANGSUNG_loading'
export const DELETE_PENUNJUKAN_LANGSUNG_SUCCESS = 'delete_PENUNJUKAN_LANGSUNG_success'
export const DELETE_PENUNJUKAN_LANGSUNG_ERROR = 'delete_PENUNJUKAN_LANGSUNG_error'
