// created
export const CREATE_UPLOAD_FINANCIAL_LOADING = 'create_UPLOAD_FINANCIAL_loading'
export const CREATE_UPLOAD_FINANCIAL_SUCCESS = 'create_UPLOAD_FINANCIAL_success'
export const CREATE_UPLOAD_FINANCIAL_ERROR = 'create_UPLOAD_FINANCIAL_error'
// updated
export const UPDATE_UPLOAD_FINANCIAL_LOADING = 'update_UPLOAD_FINANCIAL_loading'
export const UPDATE_UPLOAD_FINANCIAL_SUCCESS = 'update_UPLOAD_FINANCIAL_success'
export const UPDATE_UPLOAD_FINANCIAL_ERROR = 'update_UPLOAD_FINANCIAL_error'
// deleted
export const DELETE_UPLOAD_FINANCIAL_LOADING = 'delete_UPLOAD_FINANCIAL_loading'
export const DELETE_UPLOAD_FINANCIAL_SUCCESS = 'delete_UPLOAD_FINANCIAL_success'
export const DELETE_UPLOAD_FINANCIAL_ERROR = 'delete_UPLOAD_FINANCIAL_error'
