// created
export const CREATE_PEMBELIAN_LANGSUNG_LOADING = 'create_PEMBELIAN_LANGSUNG_loading'
export const CREATE_PEMBELIAN_LANGSUNG_SUCCESS = 'create_PEMBELIAN_LANGSUNG_success'
export const CREATE_PEMBELIAN_LANGSUNG_ERROR = 'create_PEMBELIAN_LANGSUNG_error'
// updated
export const UPDATE_PEMBELIAN_LANGSUNG_LOADING = 'update_PEMBELIAN_LANGSUNG_loading'
export const UPDATE_PEMBELIAN_LANGSUNG_SUCCESS = 'update_PEMBELIAN_LANGSUNG_success'
export const UPDATE_PEMBELIAN_LANGSUNG_ERROR = 'update_PEMBELIAN_LANGSUNG_error'
// deleted
export const DELETE_PEMBELIAN_LANGSUNG_LOADING = 'delete_PEMBELIAN_LANGSUNG_loading'
export const DELETE_PEMBELIAN_LANGSUNG_SUCCESS = 'delete_PEMBELIAN_LANGSUNG_success'
export const DELETE_PEMBELIAN_LANGSUNG_ERROR = 'delete_PEMBELIAN_LANGSUNG_error'
