// created
export const CREATE_PEMILIHAN_LANGSUNG_LOADING = 'create_PEMILIHAN_LANGSUNG_loading'
export const CREATE_PEMILIHAN_LANGSUNG_SUCCESS = 'create_PEMILIHAN_LANGSUNG_success'
export const CREATE_PEMILIHAN_LANGSUNG_ERROR = 'create_PEMILIHAN_LANGSUNG_error'
// updated
export const UPDATE_PEMILIHAN_LANGSUNG_LOADING = 'update_PEMILIHAN_LANGSUNG_loading'
export const UPDATE_PEMILIHAN_LANGSUNG_SUCCESS = 'update_PEMILIHAN_LANGSUNG_success'
export const UPDATE_PEMILIHAN_LANGSUNG_ERROR = 'update_PEMILIHAN_LANGSUNG_error'
// deleted
export const DELETE_PEMILIHAN_LANGSUNG_LOADING = 'delete_PEMILIHAN_LANGSUNG_loading'
export const DELETE_PEMILIHAN_LANGSUNG_SUCCESS = 'delete_PEMILIHAN_LANGSUNG_success'
export const DELETE_PEMILIHAN_LANGSUNG_ERROR = 'delete_PEMILIHAN_LANGSUNG_error'
