// upload
export const UPLOAD_ANGGARAN_EKSPLOITASI_LOADING = 'UPLOAD_ANGGARAN_EKSPLOITASI_loading'
export const UPLOAD_ANGGARAN_EKSPLOITASI_SUCCESS = 'UPLOAD_ANGGARAN_EKSPLOITASI_success'
export const UPLOAD_ANGGARAN_EKSPLOITASI_ERROR = 'UPLOAD_ANGGARAN_EKSPLOITASI_error'
